spring:
  application:
    name: DC-middleware

# Server
server:
  port: 8080

# OAuth2 Configuration
oauth2:
  provider:
    base-url: https://dcdevsso.dubaichamber.com
    authorize: oauth2/authorize
    authn: oauth2/authn
    token: oauth2/token
    logout: oidc/logout
  client:
    id: sq_R1zmC3lqH2EUJwsWQ8wxA7Kca
    redirect-uri: https://sampleseibelmobileapp.com/home
    scope: openid internal_login


logging:
  level:
    org:
      springframework: debug
      dubaichamber: debug
    root: ERROR


rest-ws:
  scim-user-management:
#    base-url: https://dcdigitalservicessso.dubaichamber.com
    base-url: https://dcdevsso.dubaichamber.com
    basic-auth:
      username: admin
#      password: Duba1Ch@mb3rsprd!
      password: Duba1Ch@mb3r!
    get-user:
      url: scim2/Users
    update-user:
      url: t/carbon.super/scim2/Users/{uuid}

  user-registration:
    base-url: https://dcdevsso.dubaichamber.com
    basic-auth:
      username: mobileappapiuser
      password: Duba1DccCh@mb3r!_
    self-register:
      url: api/identity/user/v1.0/me

  cp-services:
    base-url: https://dcsoafmwsit.dubaichamber.com
    headers:
      siebel-user: TESTDEV66
      basic-auth:
        username: EAIUSER
        password: EAISa#14##12
    list-values:
      url: DCCICPIntegration/ListOfValues_REST/GetListOfValues
    license-info:
      url: DCCIProfessionalLicenseDetails/MemberDataToSiebel_REST/memberdata
    validate-member-license:
      url: DCCICPIntegration/ValidateAccount_REST/ValidateAccount
    get-srs-services-fees:
      url: DCCICPIntegration/GetSrServiceFeesREST_ProxyService/GetSrServiceFees
    verify-signature:
      url: DCCICreateSVS/SVSProxyService_rest/Signature
    query-svs:
      url: DCCICreateSVS/SVSProxyService_rest/QuerySVS
    auth-cert:
      url: DCCICreateSVS/SVSProxyService_rest/AuthCert
    true-copy:
      url: DCCICreateSVS/SVSProxyService_rest/TrueCopy

